// Generated by scripts/build-worker.mjs. Edit lib/analysis.js and cloudflare/runtime.js.
/* Shared deterministic analysis; browser + Worker. No AI, no price targets. */
const RadarAnalysis = (() => {
  const num = v => typeof v === 'number' && Number.isFinite(v) && Math.abs(v) <= Number.MAX_SAFE_INTEGER ? v : null;
  const ratio = (a,b) => num(a) !== null && num(b) !== null && b > 0 ? a / b * 100 : null;
  const code = s => String(s || '').normalize('NFKC').toUpperCase().replace(/\s/g,'').replace(/^([0-9A-Z]{4})0$/, '$1');
  const rounded = n => new Intl.NumberFormat('ja-JP',{maximumFractionDigits:2}).format(n);
  const money = n => num(n) === null ? 'データなし' : Math.abs(n)>=1e8 ? rounded(n/1e8)+'億円' : Math.abs(n)>=1e4 ? rounded(n/1e4)+'万円' : rounded(n)+'円';
  const percent = n => num(n) === null ? 'データなし' : rounded(n)+'%';
  const fields = {
    orderAmount:'受注額',revenue:'前期売上高',operatingProfit:'前期営業利益',
    oldRevenue:'旧売上予想',newRevenue:'新売上予想',oldOperatingProfit:'旧営業利益予想',newOperatingProfit:'新営業利益予想',
    oldOrdinaryProfit:'旧経常利益予想',newOrdinaryProfit:'新経常利益予想',oldNetProfit:'旧純利益予想',newNetProfit:'新純利益予想',oldEps:'旧EPS',newEps:'新EPS',
    oldDividend:'旧年間配当',newDividend:'新年間配当',dividendEps:'配当と同年度のEPS',
    buybackAmount:'取得総額上限',buybackShares:'取得株数上限',buybackReportedPct:'開示記載の取得比率',marketCap:'時価総額',issuedShares:'現在の発行済株式数',
    newShares:'新規発行株式数',potentialShares:'新株予約権の潜在株式数',proceeds:'調達金額',
    acquisitionPrice:'買収金額',targetRevenue:'対象企業の売上高',targetProfit:'対象企業の年間純利益',acquiredPercent:'取得持分比率',goodwill:'のれん',cash:'現金及び現金同等物',debt:'有利子負債'
  };
  const perShare = new Set(['oldEps','newEps','oldDividend','newDividend','dividendEps']);
  const shares = new Set(['buybackShares','issuedShares','newShares','potentialShares']);
  const percentages = new Set(['buybackReportedPct','acquiredPercent']);
  function parse(value, key) {
    if (typeof value === 'number') return num(value);
    const s = String(value || '').normalize('NFKC').trim().replace(/[△▲]/g,'-');
    if (!s) return null;
    const m = s.match(/^([+-]?(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?)\s*(億|百万|千万|万|千)?\s*(円|株|%)?$/);
    if (!m) return null;
    if (shares.has(key) && m[3] && m[3] !== '株') return null;
    if (percentages.has(key) && ((m[3] && m[3] !== '%') || m[2])) return null;
    if (!shares.has(key) && !percentages.has(key) && m[3] && m[3] !== '円') return null;
    if (perShare.has(key) && m[2]) return null;
    const result = Number(m[1].replaceAll(',','')) * ({億:1e8,百万:1e6,千万:1e7,万:1e4,千:1e3}[m[2]] || 1);
    return num(result) !== null && (!shares.has(key) || (Number.isInteger(result) && result >= 0)) ? result : null;
  }
  function extract(text) {
    const values = {}, evidence = {}, conflicts = [];
    for (const line of String(text || '').normalize('NFKC').split(/\r?\n/)) {
      const m = line.trim().match(/^(.{1,40}?)\s*[:：]\s*(.+)$/);
      if (!m) continue;
      const key = Object.keys(fields).find(k=>fields[k] === m[1].trim());
      if (!key) continue;
      const value = parse(m[2],key);
      if (value === null) continue;
      if (Object.hasOwn(values,key) && values[key] !== value) conflicts.push(key);
      values[key] = value; evidence[key] = line.trim();
    }
    for (const key of conflicts) { delete values[key]; delete evidence[key]; }
    return {values,evidence,conflicts:[...new Set(conflicts)]};
  }
  function change(a,b) {
    if (num(a) === null || num(b) === null) return {value:null,text:'データなし'};
    if (a === 0) return {value:null,text:'旧値が0のため率は算出不可'};
    if (a < 0) return {value:null,text:b>0?'黒字転換':b===0?'損益均衡':b>a?'赤字縮小':b<a?'赤字拡大':'赤字額は同じ'};
    const value = (b-a)/a*100;
    return {value,text:(value>0?'+':'')+percent(value)+(b<0?'（赤字転落）':'')};
  }
  function selectFinancials(company, detail) {
    if (!company || code(company.code) !== code(detail.code)) return null;
    const date = String(detail.date || '').replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3');
    const cutoff = Date.parse(date+'T'+(detail.time || '23:59')+':59+09:00');
    if (!Number.isFinite(cutoff)) return null;
    return (company.records || []).filter(r=>r.sourceUrl && ['consolidated','standalone'].includes(r.scope) && Date.parse(r.publishedAt)<=cutoff && Date.parse(r.periodEnd)<=cutoff)
      .sort((a,b)=>b.periodEnd.localeCompare(a.periodEnd)||b.publishedAt.localeCompare(a.publishedAt))[0] || null;
  }
  function analyze(detail, company = null) {
    const f = detail.facts || {}, categories = detail.categories || [];
    const a = {version:'3.0',impact:'判定できません',sustainability:'不明',scale:'データなし',financialBurden:'不明',guidance:f.guidance==='included'?'織り込み済み':f.guidance==='excluded'?'未織り込み':'不明',metrics:[],warnings:[],checkpoints:[],provenance:[],primary:null};
    const add = (key,label,value,unit='money',note='') => {
      value=num(value); const m={key,label,value,unit,text:value===null?'データなし':unit==='pct'?percent(value):unit==='shares'?rounded(value)+'株':unit==='multiple'?rounded(value)+'倍':money(value),note};
      a.metrics.push(m); return m;
    };
    const warn = s => { if(!a.warnings.includes(s))a.warnings.push(s); };
    const point = s => { if(!a.checkpoints.includes(s))a.checkpoints.push(s); };
    const basis = selectFinancials(company,detail);
    const manualBasis = Object.hasOwn(f,'revenue') || Object.hasOwn(f,'operatingProfit');
    const revenue = num(manualBasis?f.revenue:basis?.revenue), op = num(manualBasis?f.operatingProfit:basis?.operatingProfit);
    if (manualBasis) { a.provenance.push({label:'比較用業績：利用者の確認値',period:f.financialPeriod||'対象年度未指定',url:detail.sourceUrl||detail.originalUrl||''}); if(!f.financialPeriod)warn('比較業績の対象年度を確認してください。'); }
    else if (basis) {
      a.provenance.push({label:'EDINET 有価証券報告書（加工データ）',period:basis.periodEnd+' / '+(basis.scope==='consolidated'?'連結':'単体'),url:basis.sourceUrl,publishedAt:basis.publishedAt});
      if(Date.parse(String(detail.date).replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3'))-Date.parse(basis.periodEnd)>550*864e5)warn('比較対象の決算期末から550日以上経過しています。最新の決算と照合してください。');
    }
    if (detail.sourceKind==='manual')warn('数値は利用者が原文と照合した入力値です。自動抽出の候補だけでは確定しません。');
    function scale(value, large, medium) { return num(value)===null?'データなし':Math.abs(value)>=large?'大きい':Math.abs(value)>=medium?'中程度':'小さい'; }
    if(categories.includes('大型受注')) {
      add('orderAmount','受注額',f.orderAmount); add('revenue','前期売上高',revenue); add('operatingProfit','前期営業利益',op);
      const r=ratio(f.orderAmount,revenue); a.primary=add('orderRatio','年間売上高に対する受注額',r,'pct','案件全体と単年度売上高の比較');
      const margin=ratio(op,revenue);add('margin','過去営業利益率',margin,'pct');
      const estimate=num(f.orderAmount)!==null && f.orderAmount>=0 && margin>0 ? f.orderAmount*margin/100:null;
      add('estimatedProfit','営業利益への概算寄与（案件全体）',estimate,'money','従来と同じ採算を仮定');add('estimatedProfitRatio','前期営業利益に対する概算',ratio(estimate,op),'pct','単年度の増益率ではありません');
      a.scale=scale(r,20,5);a.impact=r===null?'判定できません':a.scale==='大きい'?'大きい可能性（売上規模）':a.scale==='中程度'?'中程度の可能性（売上規模）':'限定的な可能性（売上規模）';
      a.sustainability=f.contractYears>1?'複数年度の可能性':f.contractYears===1?'1年間の案件':'不明';
      warn('概算です。実際の利益率は不明。売上計上時期・費用・為替によって寄与は変わります。');
      if(op!==null && op<=0)warn('過去営業利益が0以下のため利益寄与の概算は行いません。');
      point('契約期間：'+(f.contractPeriod||'データなし'));point('売上計上予定：'+(f.recognitionPeriod||'データなし'));point('次回決算で受注残・売上計上・案件採算を確認。');
    }
    if(categories.some(c=>['上方修正','下方修正','赤字転落'].includes(c))) {
      let primary;
      for(const [key,label] of [['Revenue','売上高'],['OperatingProfit','営業利益'],['OrdinaryProfit','経常利益'],['NetProfit','純利益'],['Eps','EPS']]) {
        const before=num(f['old'+key]),after=num(f['new'+key]);
        const diff=key==='Eps' && f.perShareComparable!==true?{value:null,text:'株式分割等の基準を確認してください'}:change(before,after);
        const m=add('revision'+key,label+'予想修正率',diff.value,'pct',money(before)+' → '+money(after));m.text=diff.text;
        if(key==='OperatingProfit')primary=m;
      }
      if(!a.primary)a.primary=primary;
      a.scale=scale(primary.value,20,5);a.impact=primary.value===null?'判定できません':a.scale+'修正（営業利益）';a.sustainability='対象予想期間内';
      point('一時損益・為替・本業の数量や採算を分けて確認。');warn('修正前が0または赤字の場合、通常の修正率を表示せず損益の変化で示します。');
    }
    if(categories.some(c=>['増配','減配'].includes(c))) {
      add('oldDividend','旧年間配当',f.oldDividend);add('newDividend','新年間配当',f.newDividend);
      const diff=f.perShareComparable===true?change(f.oldDividend,f.newDividend):{value:null,text:'株式分割等の基準を確認してください'};
      const m=add('dividendChange','年間配当の増減率',diff.value,'pct');m.text=diff.text;if(!a.primary)a.primary=m;
      add('dividendEps','配当と同年度のEPS',f.dividendEps);
      const payout=f.dividendEpsSamePeriod===true && f.perShareComparable===true?ratio(f.newDividend,f.dividendEps):null;
      add('payout','配当性向',payout,'pct');if(payout>100)warn('配当性向が100%を超えています。利益以外の原資・継続性を確認してください。');
      if(num(f.newDividend)!==null && f.newDividend>f.oldDividend && num(f.newEps)!==null && num(f.oldEps)!==null && f.newEps<=f.oldEps)warn('増配に対してEPSが増えていません。配当原資を確認してください。');
      warn('配当とEPSは同年度・同じ株数基準で比較します。赤字・EPSが0の場合は配当性向を算出しません。');point('普通配当と記念・特別配当を区別し、次年度の方針を確認。');
    }
    if(categories.includes('自社株買い')) {
      add('buybackAmount','自社株買い金額上限',f.buybackAmount);add('marketCap','時価総額',f.marketCap,'money',f.marketCapAsOf?'基準日 '+f.marketCapAsOf:'基準日なし');
      const r=/^\d{4}-\d{2}-\d{2}$/.test(f.marketCapAsOf||'')?ratio(f.buybackAmount,f.marketCap):null;
      const m=add('buybackRatio','自社株買い金額 ÷ 時価総額',r,'pct');if(!a.primary)a.primary=m;a.scale=scale(r,5,1);
      add('buybackShares','取得株数上限',f.buybackShares,'shares');add('buybackShareRatio','発行済株式数に対する取得上限',ratio(f.buybackShares,f.issuedShares),'pct','入力した発行済株式数（自己株式を含む）が分母');add('reportedRatio','開示記載の取得比率',f.buybackReportedPct,'pct','自己株式を除く等、分母を原文で確認');
      a.sustainability='取得期間内';warn('取得枠は上限です。全額の実施や消却は確約されません。直接の営業増益ではありません。');point('取得期間：'+(f.buybackPeriod||'データなし'));point('取得実績・消却予定・手元資金の変化を確認。');
    }
    if(categories.includes('希薄化')) {
      add('newShares','新規発行株式数',f.newShares,'shares');add('issuedShares','現在の発行済株式数',f.issuedShares,'shares');
      const r=ratio(f.newShares,f.issuedShares);const m=add('dilution','新規発行株式数 ÷ 現在の発行済株式数',r,'pct');if(!a.primary)a.primary=m;
      add('ownershipLoss','既存持分の減少率',num(f.newShares)!==null&&num(f.issuedShares)!==null?ratio(f.newShares,f.issuedShares+f.newShares):null,'pct','新株 ÷ 発行後株式数');
      add('potentialDilution','新株予約権の潜在希薄化率',ratio(f.potentialShares,f.issuedShares),'pct','全行使を仮定。新株発行分とは合算しません');add('proceeds','調達金額',f.proceeds);
      a.scale=scale(r,20,5);a.sustainability='発行後も株数に影響';point('資金用途：'+(f.fundUse||'データなし'));point('調達資金が利益成長につながる時期と、追加行使の状況を確認。');warn('議決権ベースの公式希薄化率とは異なることがあります。');
    }
    if(categories.includes('M&A')||categories.includes('出資・投資')) {
      add('acquisitionPrice','買収金額',f.acquisitionPrice);add('targetRevenue','対象企業の売上高',f.targetRevenue);add('targetProfit','対象企業の年間純利益',f.targetProfit);add('acquiredPercent','取得持分比率',f.acquiredPercent,'pct');
      const profit=f.acquisitionBasisConfirmed===true && f.acquiredPercent>0 && f.acquiredPercent<=100 && num(f.targetProfit)!==null?f.targetProfit*f.acquiredPercent/100:null;
      const m=add('acquisitionMultiple','買収金額 ÷ 取得持分相当の年間純利益',num(f.acquisitionPrice)!==null&&profit>0?f.acquisitionPrice/profit:null,'multiple');if(!a.primary)a.primary=m;
      add('goodwill','のれん',f.goodwill);add('cash','現金及び現金同等物',f.cash);add('debt','有利子負債',f.debt);const burden=ratio(f.acquisitionPrice,f.cash);add('cashBurden','買収金額 ÷ 現金及び現金同等物',burden,'pct');a.financialBurden=burden===null?'不明':burden>=50?'現金に対して大きい':'現金との比率を確認';
      a.sustainability='複数年度の可能性';warn('利益倍率は回収年数の予測ではありません。株式取得対価と同じ持分・利益基準か確認してください。');point('資金調達、対象会社の負債、統合費用、のれんの減損リスクを確認。');
    }
    if(categories.includes('業務提携'))point('収益モデル、具体的な契約金額、事業化時期を次の開示で確認。');
    if(categories.includes('株式分割'))warn('株式分割だけで会社全体の利益や企業価値は増えません。1株指標の基準日を確認してください。');
    if(categories.includes('TOB'))point('買付主体・価格・期間・成立条件・上場維持方針を原文で確認。');
    point('会社の業績予想への織り込み：'+a.guidance+'。次回決算で確認。');
    if(!a.metrics.some(m=>m.value!==null))warn('定量データがないため、金額・割合・業績への影響を推測しません。原文から数値を追加できます。');
    if(detail.demo)warn('これは架空のサンプルです。実際の開示・銘柄ではありません。');
    a.provenance.push({label:detail.sourceKind==='manual'?'開示原文・確認入力':'TDnet（タイトルと原文リンク）',url:detail.sourceUrl||detail.originalUrl||'',period:detail.date||''});
    a.coverage={available:a.metrics.filter(m=>m.value!==null).length,total:a.metrics.length};
    return a;
  }
  return {num,ratio,code,money,percent,rounded,fields,perShare,shares,percentages,parse,extract,change,selectFinancials,analyze};
})();
if (typeof module !== 'undefined' && module.exports) module.exports=RadarAnalysis;

const APP_BASE_URL = "https://kuma885.github.io/tdnet-radar/";
const DETAIL_TTL_SECONDS = 60 * 60 * 24 * 35;

const RULES = [
  {
    label: "上方修正",
    words: [/上方修正/, /上方に修正/, /上方へ修正/]
  },
  {
    label: "増配",
    words: [/増配/, /配当予想.*引き上げ/, /配当.*増額/]
  },
  {
    label: "自社株買い",
    words: [
      /自己株式取得に係る事項の決定/,
      /自己株式の取得に係る事項の決定/,
      /自己株式の取得及び自己株式立会外買付取引/,
      /自己株式.*買付けに関するお知らせ/
    ],
    exclude: [/取得状況/, /取得結果/, /取得終了/, /取得実績/]
  },
  {
    label: "大型受注",
    words: [
      /大型受注/,
      /大口受注/,
      /大型案件.*受注/,
      /受注獲得/,
      /大型案件.*落札/,
      /大型契約.*締結/
    ]
  },
  {
    label: "業務提携",
    words: [
      /業務提携契約/,
      /資本業務提携/,
      /事業提携/,
      /戦略的業務提携/,
      /協業開始/,
      /共同事業.*開始/
    ]
  },
  {
    label: "M&A",
    words: [
      /吸収合併/,
      /合併契約/,
      /株式交換契約/,
      /株式移転/,
      /株式取得.*子会社化/,
      /子会社化に関するお知らせ/,
      /事業譲受/,
      /事業譲渡/,
      /会社分割/,
      /連結子会社の異動/
    ]
  },
  {
    label: "TOB",
    words: [
      /公開買付けの開始/,
      /公開買付け開始/,
      /公開買付けに関する意見表明/,
      /\bTOB\b/i
    ]
  },
  {
    label: "株式分割",
    words: [/株式分割/]
  },
  {
    label: "下方修正",
    words: [/下方修正/, /下方に修正/, /下方へ修正/]
  },
  {
    label: "減配",
    words: [/減配/, /無配/, /配当予想.*引き下げ/]
  },
  {
    label: "赤字転落",
    words: [/赤字転落/, /黒字予想.*赤字/, /黒字.*赤字へ/]
  },
  {
    label: "希薄化",
    words: [
      /第三者割当.*新株式.*発行/,
      /第三者割当.*新株予約権.*発行/,
      /第三者割当増資/,
      /公募増資/,
      /行使価額修正条項付.*新株予約権.*発行/,
      /転換社債型新株予約権付社債.*発行/,
      /MSワラント.*発行/i
    ],
    exclude: [
      /月間行使状況/,
      /行使状況/,
      /行使結果/,
      /大量行使/,
      /発行状況/,
      /払込完了/
    ]
  }
];

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders()});
    if(request.method!=='GET')return jsonResponse({error:'method not allowed'},405,corsHeaders());
    if(url.pathname==='/api/detail')return getDetailResponse(url,env);
    if(url.pathname==='/api/history')return getHistoryResponse(url,env);
    if(url.pathname==='/api/legacy-history') {
      if(!env.TDNET_STATE.list)return jsonResponse({items:[],next:null},200,corsHeaders());
      const result=await env.TDNET_STATE.list({prefix:'detail:',limit:20,...(url.searchParams.get('cursor')?{cursor:url.searchParams.get('cursor').slice(0,1000)}:{})});
      const items=(await Promise.all(result.keys.map(k=>env.TDNET_STATE.get(k.name,'json')))).filter(Boolean).map(d=>({...d,analysis:RadarAnalysis.analyze(d)}));
      return jsonResponse({items,next:result.list_complete?null:result.cursor},200,corsHeaders());
    }
    // Public page reads never trigger TDnet polling. Existing Cron remains the detector.
    if(url.pathname!=='/' && url.pathname!=='/api/status')return jsonResponse({error:'not found'},404,corsHeaders());
    const date=jstDate(), saved=await env.TDNET_STATE.get('history:'+date,'json');
    return jsonResponse({version:'3.0',date,totalCount:saved?.ids?.length||0,matches:[],updatedAt:saved?.updatedAt||null,historyCount:saved?.details?.length||0,pending:saved?.pending||0,sourceMode:'existing-tdnet',financialStatus:saved?.financialStatus||'not_loaded'},200,corsHeaders());
  },
  async scheduled(controller, env, ctx) {
    const result=await readTdnetAll(); // v2 detector, parsing and title rules are unchanged.
    const key='history:'+result.date;
    let saved=await env.TDNET_STATE.get(key,'json');
    if(!saved) {
      const legacy=await env.TDNET_STATE.get('seen:'+result.date,'json');
      saved={ids:legacy?.ids||[],details:[],writes:0,initializing:!legacy,silentIds:legacy?[]:result.items.map(makeId)};
      if(!result.items.length){
        await env.TDNET_STATE.put(key,JSON.stringify({...saved,initializing:false,updatedAt:new Date().toISOString()}),{expirationTtl:90*86400});
        return;
      }
    }
    if(saved.writes>=800 || saved.details.length>=750){console.error('FREE_LIMIT: daily history capacity reached');return;}
    const known=new Set(saved.ids), pending=result.items.filter(i=>!known.has(makeId(i)));
    if(!pending.length)return;
    const financials=await loadFinancials();
    const details=[...saved.details], notify=[];
    let accepted=0;
    for(const item of pending) {
      const categories=classifyTitle(item.title);
      if(!categories.length){known.add(makeId(item));continue;}
      if(accepted>=15 || details.length>=750)continue; // <=20 TDnet + 1 finance + 15 pushes, Free subrequest ceiling.
      const id=result.date+(await makeDetailId(result.date,item)).slice(0,16);
      const detail={id,date:result.date,...item,originalUrl:safeTdnetUrl(item.originalUrl)||makeTdnetListUrl(result.date),categories,explanations:buildExplanations(item.title,categories),explanationSource:'title',createdAt:new Date().toISOString(),facts:{}};
      const company=financials.companies?.[RadarAnalysis.code(item.code)];
      const basis=RadarAnalysis.selectFinancials(company,detail);
      if(basis)detail.companyFinancials={code:RadarAnalysis.code(item.code),records:[basis]};
      details.push(detail);known.add(makeId(item));accepted++;
      if(!(saved.silentIds||[]).includes(makeId(item)))notify.push(detail);
    }
    const remaining=result.items.filter(i=>!known.has(makeId(i))).length;
    const state={ids:[...known],details,writes:saved.writes+1,initializing:!!saved.initializing&&remaining>0,silentIds:(saved.silentIds||[]).filter(id=>!known.has(id)),pending:remaining,updatedAt:new Date().toISOString(),financialStatus:financials.status||'unavailable'};
    // Persist once per changed poll, before notification. A KV error produces no duplicate push.
    await env.TDNET_STATE.put(key,JSON.stringify(state),{expirationTtl:90*86400});
    for(const detail of notify) {
      try {await sendPush(env,{...detail,analysis:RadarAnalysis.analyze(detail,detail.companyFinancials)},detail.categories,detail.id,result.date);}
      catch {console.error('Push failed; disclosure retained in history',detail.id);}
    }
  }
};

function jstDate(){return new Date(Date.now()+9*3600000).toISOString().slice(0,10).replaceAll('-','');}
function validDate(date){if(!/^\d{8}$/.test(date))return false;const iso=date.slice(0,4)+'-'+date.slice(4,6)+'-'+date.slice(6,8);return Number.isFinite(Date.parse(iso))&&new Date(iso).toISOString().slice(0,10)===iso;}
let financialCache=null,financialExpires=0;
async function loadFinancials(){
  if(financialCache&&Date.now()<financialExpires)return financialCache;
  try {
    const response=await fetch('https://raw.githubusercontent.com/kuma885/tdnet-radar/financial-data/data/financials.json',{signal:AbortSignal.timeout(12000)});
    if(!response.ok)throw Error('unavailable');
    if(Number(response.headers.get('Content-Length'))>10000000)throw Error('size');
    const raw=await response.text();if(raw.length>10000000)throw Error('size');const value=JSON.parse(raw);
    if(value.schemaVersion!==1 || !value.companies)throw Error('schema');
    financialCache=value;financialExpires=Date.now()+3600000;return value;
  }catch {financialExpires=Date.now()+300000;return financialCache||(financialCache={companies:{},status:'unavailable'});}
}
async function getHistoryResponse(url,env){
  const date=url.searchParams.get('date')||jstDate();
  if(!validDate(date))return jsonResponse({error:'invalid date'},400,corsHeaders());
  const state=await env.TDNET_STATE.get('history:'+date,'json');
  const details=state?.details||[];const offset=Math.max(0,Math.min(750,Number.parseInt(url.searchParams.get('offset'),10)||0));
  const items=details.slice().reverse().slice(offset,offset+50).map(d=>{
    const a=RadarAnalysis.analyze(d,d.companyFinancials);
    return {id:d.id,date:d.date,time:d.time,company:d.company,code:d.code,title:d.title,categories:d.categories,analysis:{impact:a.impact,primary:a.primary},originalUrl:d.originalUrl};
  });
  return jsonResponse({version:'3.0',date,items,nextOffset:offset+50<details.length?offset+50:null,updatedAt:state?.updatedAt||null,pending:state?.pending||0},200,corsHeaders());
}
async function getDetailResponse(url, env) {
  const id=url.searchParams.get('id');
  if(!id||!/^[a-f0-9]{24}$/.test(id))return jsonResponse({error:'valid id is required'},400,corsHeaders());
  let detail;
  if(validDate(id.slice(0,8))){const state=await env.TDNET_STATE.get('history:'+id.slice(0,8),'json');detail=state?.details?.find(d=>d.id===id);}
  if(!detail)detail=await env.TDNET_STATE.get('detail:'+id,'json');
  if(!detail)return jsonResponse({error:'detail not found or expired'},404,corsHeaders());
  return jsonResponse({...detail,analysis:RadarAnalysis.analyze(detail,detail.companyFinancials)},200,corsHeaders());
}

function classifyTitle(title) {
  const result = [];
  const investment = isThirdPartyInvestmentByCompany(title);

  if (investment) {
    result.push("出資・投資");
  }

  for (const rule of RULES) {
    // 「他社の第三者割当増資を当社が引き受ける」は
    // 当社自身の希薄化ではないので、希薄化判定を抑止。
    if (investment && rule.label === "希薄化") {
      continue;
    }

    if (rule.exclude && rule.exclude.some(regex => regex.test(title))) {
      continue;
    }

    if (rule.words.some(regex => regex.test(title))) {
      result.push(rule.label);
    }
  }

  return [...new Set(result)];
}

function isThirdPartyInvestmentByCompany(title) {
  const hasThirdParty = /第三者割当増資|第三者割当.*新株/.test(title);
  const companyAccepts =
    /当社.{0,20}(引き受け|引受|取得)/.test(title) ||
    /(引き受け|引受).{0,20}当社/.test(title);

  return hasThirdParty && companyAccepts;
}

// 複数材料を省略せず表示する。通知判定ルールには影響しない。
function buildExplanations(title, categories) {
  return categories.map(category => ({
    category,
    ...buildExplanation(title, [category])
  }));
}

function buildExplanation(title, categories) {
  if (categories.includes("出資・投資") && isThirdPartyInvestmentByCompany(title)) {
    return {
      headline: "他社への出資・投資です",
      summary:
        "他社が発行する新株などを、この会社が引き受ける（買う）という内容です。会社自身が第三者割当増資をする話ではありません。",
      points: [
        "この会社は「お金を出す側」です。",
        "このタイトルだけを見る限り、自社株の希薄化を直接意味する開示ではありません。",
        "投資額・取得比率・投資先の財務状況・目的は原文で確認すると判断しやすいです。"
      ],
      caution:
        "これはタイトルからの自動説明です。投資の良し悪しや金額の大きさまでは原文を確認してください。"
    };
  }

  if (categories.includes("自社株買い")) {
    return {
      headline: "会社が自社株を買い戻す決定です",
      summary:
        "会社自身が市場などから自社株を取得する方針を決めた開示です。",
      points: [
        "取得する株数・金額の上限を見ると規模感が分かります。",
        "取得期間も確認すると、いつまで買う予定か分かります。"
      ],
      caution:
        "取得枠は上限であり、必ず全額・全株数を買うとは限りません。"
    };
  }

  if (categories.includes("株式分割")) {
    return {
      headline: "1株を複数株に分ける開示です",
      summary:
        "保有価値そのものを増やす施策ではありませんが、1株あたりの価格を下げて売買しやすくする目的などで行われます。",
      points: [
        "「1株を何株に分割するか」を確認してください。",
        "基準日と効力発生日も重要です。"
      ],
      caution:
        "株式分割だけで企業価値そのものが増えるわけではありません。"
    };
  }

  if (categories.includes("TOB")) {
    return {
      headline: "公開買付け（TOB）に関する開示です",
      summary:
        "特定の買付者が、価格と期間を示して株式をまとめて買い付ける案件に関する情報です。",
      points: [
        "買付価格はいくらか。",
        "誰が誰を買うのか。",
        "買付期間と上場維持・上場廃止の予定があるか。"
      ],
      caution:
        "「訂正」の開示の場合は、どの条件が変更されたか原文確認が必要です。"
    };
  }

  if (categories.includes("上方修正")) {
    return {
      headline: "会社予想を上向きに見直した開示です",
      summary:
        "従来の業績予想などを、より高い数字へ修正した内容です。",
      points: [
        "売上高だけでなく営業利益・経常利益・最終利益の修正幅を確認してください。",
        "一時的な要因か、本業の改善かも重要です。"
      ],
      caution:
        "タイトルだけでは修正幅までは分かりません。原文の新旧予想値を確認してください。"
    };
  }

  if (categories.includes("下方修正")) {
    return {
      headline: "会社予想を下向きに見直した開示です",
      summary:
        "従来の業績予想などを、より低い数字へ修正した内容です。",
      points: [
        "営業利益・経常利益・最終利益の下げ幅を確認してください。",
        "原因が一時的か継続的かを見ると影響を判断しやすいです。"
      ],
      caution:
        "タイトルだけでは修正幅や原因までは分かりません。"
    };
  }

  if (categories.includes("増配")) {
    return {
      headline: "配当を増やす開示です",
      summary:
        "従来予想より配当金を増やす、または増配を決めた内容です。",
      points: [
        "1株あたり配当が何円から何円になるか確認してください。",
        "記念配当など一時的な増配か、普通配当の増額かも重要です。"
      ],
      caution:
        "翌期以降も同じ配当が続くとは限りません。"
    };
  }

  if (categories.includes("減配")) {
    return {
      headline: "配当を減らす開示です",
      summary:
        "従来予想より配当金を減らす、または無配にする内容です。",
      points: [
        "1株あたり何円減るか確認してください。",
        "業績悪化・財務改善など、減配理由を見ることが重要です。"
      ],
      caution:
        "一時的な減配か、配当方針そのものの変更かで意味が変わります。"
    };
  }

  if (categories.includes("希薄化")) {
    return {
      headline: "新株発行などによる希薄化に関係する開示です",
      summary:
        "新しい株式や新株予約権などを発行し、既存株主の1株あたり持分が薄まる可能性がある内容です。",
      points: [
        "新たに発行される株数・潜在株数を確認してください。",
        "調達金額と資金使途も重要です。",
        "発行済株式数に対して何％増えるかを見ると規模感が分かります。"
      ],
      caution:
        "タイトルだけの判定なので、発行主体や条件によっては意味が異なる場合があります。"
    };
  }

  if (categories.includes("大型受注")) {
    return {
      headline: "大きな受注・契約を獲得した開示です",
      summary:
        "会社が大口案件を受注・落札したことに関する情報です。",
      points: [
        "受注金額を年間売上高と比べるとインパクトを判断しやすいです。",
        "売上・利益に計上される時期も確認してください。"
      ],
      caution:
        "受注金額がそのまま利益になるわけではありません。"
    };
  }

  if (categories.includes("業務提携")) {
    return {
      headline: "他社との提携・協業に関する開示です",
      summary:
        "他社と事業を一緒に進める、共同開発するなどの関係を作る内容です。",
      points: [
        "相手企業と具体的に何をするのか。",
        "売上や利益への影響時期が示されているか。"
      ],
      caution:
        "提携発表だけでは業績への具体的な効果がまだ分からない場合があります。"
    };
  }

  if (categories.includes("M&A")) {
    return {
      headline: "買収・合併・子会社化などに関する開示です",
      summary:
        "会社や事業を取得・統合・売却するなど、企業構造が変わる案件です。",
      points: [
        "誰が誰を取得するのか。",
        "取得金額や持株比率。",
        "業績への影響と資金調達方法。"
      ],
      caution:
        "案件の規模や条件によって影響が大きく変わるので原文確認が重要です。"
    };
  }

  if (categories.includes("赤字転落")) {
    return {
      headline: "利益が赤字になることに関する開示です",
      summary:
        "黒字から損失へ転じる、または損失を計上する内容です。",
      points: [
        "営業損失なのか、特別損失など一時要因なのか確認してください。",
        "通期業績への影響も重要です。"
      ],
      caution:
        "一時的な損失と本業の悪化では意味が大きく違います。"
    };
  }

  return {
    headline: "重要開示を検出しました",
    summary: "タイトルから重要そうな開示を検出しました。",
    points: [
      "内容の詳細はTDnet原文で確認してください。"
    ],
    caution:
      "これはAIを使わないルールベースの自動説明です。"
  };
}

function makeId(item) {
  return `${item.time}|${item.code}|${item.title}`;
}

async function makeDetailId(date, item) {
  const input = `${date}|${makeId(item)}`;
  const bytes = new TextEncoder().encode(input);
  const hash = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(hash)]
    .slice(0, 12)
    .map(b => b.toString(16).padStart(2, "0"))
    .join("");
}

async function readTdnetAll() {
  const nowJst = new Date(Date.now() + 9 * 60 * 60 * 1000);
  const date = nowJst.toISOString().slice(0, 10).replaceAll("-", "");

  const allItems = [];
  const maxPages = 20;

  for (let page = 1; page <= maxPages; page++) {
    const pageNo = String(page).padStart(3, "0");
    const url = `https://www.release.tdnet.info/inbs/I_list_${pageNo}_${date}.html`;

    const response = await fetch(url, {
      headers: {
        "User-Agent": "TDnet-Radar/2.1"
      }
    });

    if (!response.ok) {
      break;
    }

    const html = await response.text();
    const rows = html.match(/<tr[\s\S]*?<\/tr>/gi) || [];
    const pageItems = [];

    for (const row of rows) {
      const time = getCell(row, "kjTime");
      const code = getCell(row, "kjCode");
      const company = getCell(row, "kjName");
      const title = getCell(row, "kjTitle");
      const originalUrl = getLink(row, "kjTitle");

      if (!time || !code || !company || !title) {
        continue;
      }

      pageItems.push({
        time,
        code,
        company,
        title,
        originalUrl: originalUrl || url
      });
    }

    if (pageItems.length === 0) {
      break;
    }

    allItems.push(...pageItems);

    if (pageItems.length < 100) {
      break;
    }
  }

  return { date, items: allItems };
}

function getCell(row, className) {
  const regex = new RegExp(
    `<td[^>]*class=["'][^"']*${className}[^"']*["'][^>]*>([\\s\\S]*?)<\\/td>`,
    "i"
  );

  const match = row.match(regex);
  if (!match) return "";

  return decodeHtml(
    match[1]
      .replace(/<[^>]+>/g, "")
      .replace(/\s+/g, " ")
      .trim()
  );
}

function getLink(row, className) {
  const regex = new RegExp(
    `<td[^>]*class=["'][^"']*${className}[^"']*["'][^>]*>([\\s\\S]*?)<\\/td>`,
    "i"
  );

  const cellMatch = row.match(regex);
  if (!cellMatch) return "";

  const hrefMatch = cellMatch[1].match(/<a[^>]*href=["']([^"']+)["']/i);
  if (!hrefMatch) return "";

  const href = decodeHtml(hrefMatch[1].trim());

  try {
    return safeTdnetUrl(new URL(href, "https://www.release.tdnet.info/inbs/").href);
  } catch {
    return "";
  }
}

// 通知・リンクに使うのはTDnetのHTTPS原文/一覧だけ。
function safeTdnetUrl(value) {
  try {
    const url = new URL(value);
    if (url.protocol !== "https:" || url.hostname !== "www.release.tdnet.info" ||
        url.username || url.password || url.port || !url.pathname.startsWith("/inbs/")) return "";
    return url.href;
  } catch { return ""; }
}

function makeTdnetListUrl(date) {
  return `https://www.release.tdnet.info/inbs/I_list_001_${date}.html`;
}

function decodeHtml(text) {
  return text
    .replaceAll("&amp;", "&")
    .replaceAll("&lt;", "<")
    .replaceAll("&gt;", ">")
    .replaceAll("&quot;", '"')
    .replaceAll("&#39;", "'");
}

async function sendPush(env, item, categories, detailId, date) {
  const originalUrl = safeTdnetUrl(item.originalUrl) || makeTdnetListUrl(date);
  const detailLink = new URL("detail.html", APP_BASE_URL);
  detailLink.search = new URLSearchParams({ id: detailId, date, original: originalUrl }).toString();
  const detailUrl = detailLink.href;

  const body = {
    app_id: env.ONESIGNAL_APP_ID,
    include_subscription_ids: [
      env.ONESIGNAL_SUBSCRIPTION_ID
    ],
    headings: {
      en: `TDnetレーダー【${categories.join("・")}】`
    },
    contents: {
      en: `${item.company}（${item.code}）\n${item.analysis?.primary?.value != null ? item.analysis.primary.label + "：" + item.analysis.primary.text : "定量データなし・確認ポイントを表示"}\n中長期の影響を確認`
    },
    // Web PushはOneSignalの専用SWがこのURLを開く。
    url: detailUrl,
    web_buttons: [{ id: "original", text: "開示原文", url: originalUrl }]
  };

  const response = await fetch(
    "https://api.onesignal.com/notifications",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Key ${env.ONESIGNAL_API_KEY}`
      },
      body: JSON.stringify(body)
    }
  );

  const result = await response.json();
  console.log("OneSignal response:", JSON.stringify(result));

  if (!response.ok) {
    console.error("OneSignal送信失敗:", response.status, result);
    throw new Error("OneSignal push failed");
  }

  if (!result.id) {
    console.error("通知は作成されませんでした:", result);
    throw new Error("OneSignal returned no notification id");
  }

  console.log("OneSignal送信成功:", result.id);
  return result;
}

function jsonResponse(data, status = 200, extraHeaders = {}) {
  return new Response(
    JSON.stringify(data, null, 2),
    {
      status,
      headers: {
        "content-type": "application/json; charset=UTF-8",
        ...extraHeaders
      }
    }
  );
}

function corsHeaders() {
  return {
    "Cache-Control": "no-store",
    "Access-Control-Allow-Origin": "https://kuma885.github.io",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type"
  };
}
