import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const result='// Generated by scripts/build-worker.mjs. Edit lib/analysis.js and cloudflare/runtime.js.\n'+await readFile(new URL('lib/analysis.js',root),'utf8')+'\n'+await readFile(new URL('cloudflare/runtime.js',root),'utf8');
if(process.argv.includes('--check')){if(result!==await readFile(new URL('cloudflare/worker.js',root),'utf8'))throw Error('Run npm run build before committing');}
else await writeFile(new URL('cloudflare/worker.js',root),result);
